chore: Brands Studio to purple and sets theme color to match
redwoodjs/studio pull request #35
Opened 2024-02-19 21:49 UTC by dthyresson

This PR changes the favicon to purple and then rebrands the theme from orange to purple to match. which looks nice in dark mode and plays well with the Orbit community search.

* favicon generated
* index html updated

To make the look more consistent, it

* uses "tremor" classes to set text colors to respect light dark themed text (error messages, nav menu items)
* uses a svg icon for the StudioIcon so it can automatically be set with the theme

2024-02-26 16:17 UTC, Tobbe requested changes

2024-02-26 16:17 UTC, Tobbe commented on web/public/mark.svg
Why is this one so tiny now? And do we want it to be purple instead?

2024-02-26 16:17 UTC, Tobbe commented on artwork/favicon-purple/android-chrome-512x512.png
Can you use our svg as a base instead? The png looks very blurry when scaled up like this.

2024-02-26 16:17 UTC, Tobbe commented on artwork/favicon/android-chrome-192x192.png
Do we need this orange version? What is it used for?

2024-02-27 08:09 UTC, Tobbe commented
I've made some changes to this PR:
* Updated the favicon images to be higher quality
* Used https://realfavicongenerator.net to generate images/icons and html code to best support various browsers and devices. (Highest ranking answers on StackOverflow ([1](https://stackoverflow.com/questions/48956465/favicon-standard-2024-svg-ico-png-and-dimensions), [2](https://stackoverflow.com/questions/25952907/what-is-the-best-practice-for-creating-a-favicon-on-a-web-site)) both point to that generator)

I used the attached SVG as a starting point when generating the icons. I then filled it with Tailwind's violet-700 color and added a drop shadow. Finally I centered the entire icon (including the drop shadow) in a 1000x1000px png file)

![diecut_mark](https://github.com/redwoodjs/studio/assets/30793/2b6a90aa-bf70-4c0e-9bcf-a4423c49f0a6)

2024-02-27 08:12 UTC, Tobbe commented
What's left to do now before this can be merged is to change it back to use a larger icon for the logo in the top-left, to match what we already have for the current version
<img width="466" alt="image" src="https://github.com/redwoodjs/studio/assets/30793/a1435912-88ac-4350-8e2c-e724a8ee54d4">

2024-02-27 08:13 UTC, Tobbe commented on web/public/mark.svg
This is not used, so I removed it

2024-02-27 08:13 UTC, Tobbe commented on artwork/favicon/android-chrome-192x192.png
It's not used, I removed it.

2024-02-27 08:13 UTC, Tobbe commented on artwork/favicon-purple/android-chrome-512x512.png
Fixed the image quality issues.

2024-02-28 14:46 UTC, dthyresson commented
> What's left to do now before this can be merged is to change it back to use a larger icon for the logo in the top-left, to match what we already have for the current version
> <img alt="image" width="466" src="https://private-user-images.githubusercontent.com/30793/308087760-a1435912-88ac-4350-8e2c-e724a8ee54d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMzA0ODksIm5iZiI6MTcwOTEzMDE4OSwicGF0aCI6Ii8zMDc5My8zMDgwODc3NjAtYTE0MzU5MTItODhhYy00MzUwLThlMmMtZTcyNGE4ZWU1NGQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE0MjMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkY2JlOWI4ZjEzYzcyNzYxMzU2OTg2MDgxZjg2ZmU4ODI0MjBiZDdlZThlM2Q1OWYyMGFjYTIzNjEzYjEwOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fu5LYTJ4Kgt0H97-JkclbO8Fv87Ei_1Wcu74RWimwfA">

Reworked markup and doesn't use Icon component:

![image](https://github.com/redwoodjs/studio/assets/1051633/5bcb1334-a096-4c05-82aa-ff938d9f2994)

2024-02-28 14:53 UTC, dthyresson commented
Thoughts on using the svg that has the white stroke outline? I only saw pngs for that image.

2024-02-28 15:19 UTC, Tobbe commented
> Thoughts on using the svg that has the white stroke outline? I only saw pngs for that image.

You can try if you want! :)  The .svg is attached to a reply here on this PR a few posts up. It has the red color, but should be easy enough to switch to violet

2024-02-28 21:15 UTC, dthyresson commented
> > Thoughts on using the svg that has the white stroke outline? I only saw pngs for that image.
> 
> You can try if you want! :) The .svg is attached to a reply here on this PR a few posts up. It has the red color, but should be easy enough to switch to violet

Yes, I prefer that:

![image](https://github.com/redwoodjs/studio/assets/1051633/d41028c9-4cef-4786-8ccf-547f9ac54044)

2024-02-29 04:09 UTC, Tobbe commented
> Yes, I prefer that:

I agree. That looks nicer 🙂

2024-02-29 04:39 UTC, merged

2024-02-29 04:47 UTC, Tobbe commented
@dthyresson I understand that you wanted to keep the title text aligned with the text for the menu items.

![studio-icon-ss](https://github.com/redwoodjs/studio/assets/30793/c8748757-ceca-4331-b9e4-5b57a189ca3a)

But I thought it looked too cramped. So I decided to keep the spacing between icon and text consistent, instead of the alignment.

<img width="343" alt="studio-dist" src="https://github.com/redwoodjs/studio/assets/30793/6709a82a-e7a9-4cdf-81ce-2f7e76b10204">